class Strings {
  static const List<String> Yemek1 = [
    "",
    "",
    "",
    "",
    "",
    "Mercimek Çorba",
    "Yayla Çorba",
    "Bugün",
    "Bugün",
    "Tarhana Çorba",
    "Mantar Çorba",
    "Mercimek Çorba",
    "Brokoli Çorba",
    "Domates Çorba",
    "Bugün",
    "Bugün",
    "Tavuksuyu Çorba",
    "Şehriye Çorba",
    "Sebze Çorba",
    "Mercimek Çorba",
    "Yoğurt Çorba",
    "Bugün",
    "Bugün",
    "Yayla Çorba",
    "Mantar Çorba",
    "Mercimek Çorba",
    "Tavuksuyu Çorba",
    "Tarhana Çorba",
    "Bugün",
    "Bugün",
  ];

  static const List<String> Yemek2 = [
    "",
    "",
    "",
    "",
    "",
    "Tavuk Fileminyom",
    "İzmir Köfte",
    "Hafta",
    "Hafta",
    "Kıymalı Mercimek",
    "Orman Kebabı",
    "Kıymalı Karnabahar",
    "Sebzeli Köfte",
    "Tavuk Döner",
    "Hafta",
    "Hafta",
    "Taze Fasulye",
    "Arnavut Tavuk",
    "Izgara Köfte",
    "Kuru Fasulye",
    "Macar Gulaş",
    "Hafta",
    "Hafta",
    "Kıymalı Ispanak",
    "Fırın Köfte",
    "Sebzeli Kebap",
    "Etli Nohut",
    "Parmak Bonfile",
    "Hafta",
    "Hafta",
  ];

  static const List<String> Yemek3 = [
    "",
    "",
    "",
    "",
    "",
    "Spagetti",
    "Makarna",
    "Sonu",
    "Sonu",
    "Su Böreği",
    "Bulgur Pilavı",
    "Pirinç Pilavı",
    "Erişte",
    "Bulgur Pilavı",
    "Sonu",
    "Sonu",
    "Pirinç Pilavı",
    "Makarna",
    "Meyhane Pilavı",
    "Pirinç Pilavı",
    "Bulgur Pilavı",
    "Sonu",
    "Sonu",
    "Su Böreği",
    "Makarna",
    "Pirinç Pilavı",
    "Bulgur Pilavı",
    "Bulgur Pilavı",
    "Spagetti",
    "Sonu",
    "Sonu",
  ];

  static const List<String> Yemek4 = [
    "",
    "",
    "",
    "",
    "",
    "Ayran",
    "Muhallebi",
    "mlsf",
    "mlsf",
    "Baklava",
    "Meyve",
    "Yoğurt",
    "Ayran",
    "Puding",
    "mlsf",
    "mlsf",
    "Meyve",
    "Şekerpare",
    "Ayran",
    "Yoğurt",
    "Sütlaç",
    "mlsf",
    "mlsf",
    "Sarı Burma",
    "Ayran",
    "Yoğurt",
    "Meyve",
    "İrmik Tatlısı",
    "mlsf",
    "mlsf",
  ];
}
