class Strings {
  static const List<String> Yemek1 = [
    "Tarhana Çorba",
    "Mantar Çorba",
    "Mercimek Çorba",
    "Brokoli Çorba",
    "Domates Çorba",
    "Mercimek Çorba",
    "Yayla Çorba",
    "",
    "",
    "Tarhana Çorba",
    "Mantar Çorba",
    "Mercimek Çorba",
    "Brokoli Çorba",
    "Domates Çorba",
    "",
    "",
    "Tavuksuyu Çorba",
    "Şehriye Çorba",
    "Sebze Çorba",
    "Mercimek Çorba",
    "Yoğurt Çorba",
    "",
    "",
    "Yayla Çorba",
    "Mantar Çorba",
    "Mercimek Çorba",
    "Tavuksuyu Çorba",
    "Tarhana Çorba",
    "",
    "",
  ];

  static const List<String> Yemek2 = [
    "Kıymalı Mercimek",
    "Orman Kebabı",
    "Kıymalı Karnabahar",
    "Sebzeli Köfte",
    "Tavuk Döner",
    "Tavuk Fİleminyom",
    "İzmir Köfte",
    "",
    "",
    "Kıymalı Mercimek",
    "Orman Kebabı",
    "Kıymalı Karnabahar",
    "Sebzeli Köfte",
    "Tavuk Döner",
    "",
    "",
    "Taze Fasulye",
    "Arnavut Tavuk",
    "Izgara Köfte",
    "Kuru Fasulye",
    "Macar Gulaş",
    "",
    "",
    "Kıymalı Ispanak",
    "Fırın Köfte",
    "Sebzeli Kebap",
    "Etli Nohut",
    "Parmak Bonfile",
    "",
    "",
  ];

  static const List<String> Yemek3 = [
    "Su Böreği",
    "Bulgur Pilavı",
    "Pirinç Pilavı",
    "Erişte",
    "Bulgur Pilavı",
    "Spagetti",
    "Makarna",
    "",
    "",
    "Su Böreği",
    "Bulgur Pilavı",
    "Pirinç Pilavı",
    "Erişte",
    "Bulgur Pilavı",
    "",
    "",
    "Pirinç Pilavı",
    "Makarna",
    "Meyhane Pilavı",
    "Pirinç Pilavı",
    "Bulgur Pilavı",
    "",
    "",
    "Su Böreği",
    "Makarna",
    "Pirinç Pilavı",
    "Bulgur Pilavı",
    "Bulgur Pilavı",
    "Spagetti",
    "",
    "",
  ];

  static const List<String> Yemek4 = [
    "Baklava",
    "Meyve",
    "Yoğurt",
    "Ayran",
    "Puding",
    "Ayran",
    "Muhallebi",
    "",
    "",
    "Baklava",
    "Meyve",
    "Yoğurt",
    "Ayran",
    "Puding",
    "",
    "",
    "Meyve",
    "Şekerpare",
    "Ayran",
    "Yoğurt",
    "Sütlaç",
    "",
    "",
    "Sarı Burma",
    "Ayran",
    "Yoğurt",
    "Meyve",
    "İrmik Tatlısı",
    "",
    "",
  ];

  static const List<String> vejeteryan = [
    "Kıymalı Mercimek",
    "Orman Kebabı",
    "Kıymalı Karnabahar",
    "Sebzeli Köfte",
    "Tavuk Döner",
    "Tavuk Fileminyom",
    "İzmir Köfte",
    "",
    "",
    "Kıymalı Mercimek",
    "Orman Kebabı",
    "Kıymalı Karnabahar",
    "Sebzeli Köfte",
    "Tavuk Döner",
    "",
    "",
    "Taze Fasulye",
    "Arnavut Tavuk",
    "Izgara Köfte",
    "Kuru Fasulye",
    "Macar Gulaş",
    "",
    "",
    "Kıymalı Ispanak",
    "Fırın Köfte",
    "Sebzeli Kebap",
    "Etli Nohut",
    "Parmak Bonfile",
    "",
    "",
  ];
}
