// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvs6U6AYTkiUS3QAQTQrHCEaJHQ6xiscM',
    appId: '1:734436895037:web:f24e69ead4bd40066afd54',
    messagingSenderId: '734436895037',
    projectId: 'yemektenevar',
    authDomain: 'yemektenevar.firebaseapp.com',
    storageBucket: 'yemektenevar.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA21ssSW2nn_-HVNSk7fXfiLzECRHQTTTM',
    appId: '1:734436895037:android:03ea69ae166092ae6afd54',
    messagingSenderId: '734436895037',
    projectId: 'yemektenevar',
    storageBucket: 'yemektenevar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8CuL_cKKD85SWDLlIwWv8GazYlzruh48',
    appId: '1:734436895037:ios:7afaee8f94d6c7bb6afd54',
    messagingSenderId: '734436895037',
    projectId: 'yemektenevar',
    storageBucket: 'yemektenevar.appspot.com',
    iosClientId: '734436895037-ceugcdcs69h5iqq8sk01oof43t5r0qmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.yemektenevar',
  );
}
